### ISSUE TITLE
`matBadge` stopped working after upgdate from 28.1.0 to 29.0.0

### ISSUE THREAD

**Issue by rosensama** [ng-icons/ng-icons#127]
**Describe the bug**
`<ng-icon matBadge="3" name="matMoreVert" />`  should display a badge on the icon.  When using ng-icons 28.1.0 it does.  When using 29.0.0, it no longer does. 

**To Reproduce**
1. @angular/cli 18.0
2. @angular/material 18.0
3. @ng-icons/core and @ng-icons/material-icons 28.1.0
4. See badge on `<ng-icon>` tag above
5. Update @ng-icons to 29.0.0
6. Badge no longer renders

**Expected behavior**
The badge should still display when using 29.0.0

**Screenshots**
28.1.0
<img width="40" alt="image" src="https://github.com/user-attachments/assets/6393c4cc-811e-493a-8029-a3a3f3a94d21">
29.0.0
<img width="40" alt="image" src="https://github.com/user-attachments/assets/55ef123d-9879-4b1a-b5c3-e382b3719938">

**Browser (please complete the following information):**
 - OS: MacOS 14.5
 - Browser Chrome
 - Version 126

**Packages (please complete the following information):**
 - @ng-icons/core 29.0.0
 - @ng-icons/material-icons 29.0.0
 - @angular 18.0 
 - @angular/material 18.0

**Comment by ashley-hunter** [comment]
Thank you for your bug report. This should now be fixed as part of #128 which I will release shortly (v29.1.0).

We were previously using innerHTML, which replaces the entire content with the SVG. This could be problematic when using things like the material badge component which appends the badge as a child. Prior to version 29 this did work, but only by coincidence rather than by design.

This should now selectively append and remove the svg element, retaining all other children.
