### ISSUE TITLE
Feature request: icons stacking

### ISSUE THREAD

**Issue by sebagallo** [ng-icons/ng-icons#149]
**Describe the bug**
Would like for this library to support icons stacking, similar to: https://docs.fontawesome.com/web/style/stack so we can move our project to this library from fortawesome.

Why? The usecase is really simple: overlaying the 'slash' icon on top of any other icon would be an example.

**Expected behavior**
Be able to pass to the component multiple icons, and have them overlayed/stacked in the order I pass them. Maybe also accept offset params for x/y for each icon you pass in order to adjust the overlaying? This is really more of an extra.

**Comment by ashley-hunter** [comment]
I have added experimental support for an icon stack component. It can be used in the following way:

<ng-icon-stack size="32px">
  <ng-icon name="faCircle" />
  <ng-icon name="faFlag" size="16px" />
</ng-icon-stack>

The size must be defined on the ng-icon-stack component. Any icons within the stack will inherit this size unless it is overridden.

I have not added any offset functionality into the components because this can simply be achieved using CSS rather than bloating the component further.

If you have any feedback let me know, thanks.
