### ISSUE TITLE
Generic type 'ɵɵComponentDeclaration' requires between 7 and 8 type arguments.

### ISSUE THREAD

**Issue by NerminKarapandzic** [ng-icons/ng-icons#50]
I just followed the getting started guide and I get this error while compiling.
Same thing happens for both module based and standalone approach.

Angular version 14.2.12
ng-icons version 23.1.0

The exact error:

```
node_modules/@ng-icons/core/lib/icon.component.d.ts:20:18 - error TS2707: Generic type 'ɵɵComponentDeclaration' requires between 7 and 8 type arguments.        

20     static ɵcmp: i0.ɵɵComponentDeclaration<NgIconComponent, "ng-icon", never, { "name": "name"; "size": "size"; "strokeWidth": "strokeWidth"; "color": "color"; }, {
}, never, never, true, never>;
```

**Comment by ashley-hunter** [comment]
Hi,

Thanks for the feedback! This issue is due to the difference in template instructions between angular 14 and angular 15.

As a result we dropped support for Angular 14 in v23.

You can verify the appropriate version of ng-icons based on your version of angular here:
https://github.com/ng-icons/ng-icons#supported-versions

This issue should be resolved by installing v22 of ng-icons or updating your version of Angular.

Thanks! Let me know if that does not resolve your issue.
